# Generated by Django 5.1.5 on 2025-02-23 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_listings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='startBid',
            new_name='bid',
        ),
    ]
