# Generated by Django 5.1.5 on 2025-02-24 18:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_listings_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='watchList',
            field=models.ManyToManyField(blank=True, related_name='WatchList', to=settings.AUTH_USER_MODEL),
        ),
    ]
